import { Group, Tabs } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { ActiveCard } from "../components/activeCard";
import { Board } from "../components/board";
import { CardContainer } from "../components/cardContainer";
import { NewCardContainer } from "../components/newCardContainer";

import { api } from "../utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const [activeTab, setActiveTab] = useState<string | null>('board');

  return (
    <>
    <Head>
        <title>Tasks</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Tabs variant="outline" defaultValue="board" onTabChange={setActiveTab} className={"w-screen h-screen flex flex-col"}>
        <Tabs.List className={"flex justify-center"}>
            <Tabs.Tab value="board">Board</Tabs.Tab>
            <Tabs.Tab value="focus">focus</Tabs.Tab>
        </Tabs.List>

        <Tabs.Panel value="board" pt="xs" className={activeTab === "board" ? "w-screen h-full p-10 scrollbar scrollbar-none" : ""}>
          <Board/>
        </Tabs.Panel>

        <Tabs.Panel value="focus" pt="xs" className={activeTab==="focus"?"w-screen h-full p-10 flex gap-3":""}>
        </Tabs.Panel>

        
    </Tabs>
    </>
  );
};

export default Home;
