import { Tabs } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import { CardContainer } from "../components/cardContainer";

import { api } from "../utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
    <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Tabs variant="outline" defaultValue="board" className={"w-screen h-screen flex flex-col"}>
        <Tabs.List className={"flex justify-center"}>
            <Tabs.Tab value="board">Gallery</Tabs.Tab>
            <Tabs.Tab value="focus">focus</Tabs.Tab>
        </Tabs.List>

        <Tabs.Panel value="board" pt="xs" className={"w-screen h-full p-10"}>
            <CardContainer/>
        </Tabs.Panel>
    </Tabs>
    </>
  );
};

export default Home;
